### PR TITLE
Upgraded Java version

### PR DESCRIPTION
**Pull request by GuidoDechamps**
- Removed Eclipse project files
- Added maven wrapper
- Upgraded to java 17 and unit 5

### CODE REVIEW

**Comment by jbrains** [comment]
Thank you for this submission; however, you seem to have combined improvements for the Java version and the Kotlin version together. Please separate those into two pull requests: one for Java and one for Kotlin.

**Comment by jbrains** [comment]
I'm not convinced that we should upgrade the Java version to Java 17. That seems like a very recent version of Java for legacy code.

I can be satisfied with upgrading to JUnit 5, so I would prefer perhaps an older version of Java which also works with JUnit 5. I'm not sure how recent this should be. What are common versions of Java code which is 3-5 years old as of 2021?

**Comment by GuidoDechamps** [comment]
Oops, the intention was indeed to do Kotlin in a separate pull request.

You could go for java 11 or 13. I indeed went for the latest version to allow every fancy refactor.

**Comment by jbrains** [comment]
I liked Java 11 and I'm going to propose a few small changes to #63. 

Please submit a new pull request for Kotlin when you have the energy.

Thank you!

**Pull request closed without merging**
