### PR TITLE
Added typescript version

### PR DESCRIPTION
**Pull request by felixble**
I decided to create a typescript version since there are some differences to the javascript / node.js versions.

### CODE REVIEW

**Comment by jbrains** [comment]
Thank you very much for this.

**Comment by jbrains** [comment]
I wonder if it's possible to add anything to this version that you would find in typical-but-slightly-badly-written Typescript. If you have any ideas, then please share them!

**Comment by felixble** [comment]
@jbrains Thanks for merging in ;-). Maybe one could remove the type definitions or replace them with `any` 🤔 ?

**Comment by jbrains** [comment]
Make them inconsistent! Make them annoyingly precise!

**Pull request merged**
